/**
 * Build script for NeoFermi CLI binary
 *
 * Two-phase build:
 *   Phase 1: Bundle client-viz.ts into a browser IIFE string
 *   Phase 2: Bundle the CLI (which imports the generated string)
 *
 * Use --watch flag for development mode.
 */

import { build, context } from 'esbuild'
import { readFile, writeFile } from 'fs/promises'
import { fileURLToPath } from 'url'
import { dirname, resolve } from 'path'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)
const projectRoot = resolve(__dirname, '..')

const watchMode = process.argv.includes('--watch')

// Phase 1: Bundle the browser viz script into a string constant
const vizBuildOptions = {
  entryPoints: [resolve(projectRoot, 'src/cli/assets/client-viz.ts')],
  bundle: true,
  platform: 'browser',
  target: 'es2020',
  format: 'iife',
  minify: true,
  write: false,
}

// Only write when the content changed, so the Phase 2 watcher (which has the
// generated file in its module graph) isn't triggered by no-op rebuilds.
async function writeGeneratedViz(result) {
  const code = result.outputFiles[0].text
  const generated = `// AUTO-GENERATED by scripts/build-cli.js — do not edit\nexport const clientVizScript = ${JSON.stringify(code)}\n`
  const outPath = resolve(projectRoot, 'src/cli/assets/_generated-client-viz.ts')
  const existing = await readFile(outPath, 'utf-8').catch(() => null)
  if (existing !== generated) {
    await writeFile(outPath, generated, 'utf-8')
  }
}

async function buildClientViz() {
  const result = await build(vizBuildOptions)
  await writeGeneratedViz(result)
}

// Phase 2: Bundle the CLI
const cliBuildOptions = {
  entryPoints: [resolve(projectRoot, 'src/cli/index.ts')],
  bundle: true,
  platform: 'node',
  target: 'node18',
  outfile: resolve(projectRoot, 'bin/neoferminb.cjs'),
  format: 'cjs',
  banner: {
    js: '#!/usr/bin/env node',
  },
  external: [
    'fsevents',
    'open',
  ],
  minify: false,
  sourcemap: true,
}

async function buildCli() {
  // Always run Phase 1 first
  console.log('Phase 1: Bundling client-viz...')
  await buildClientViz()

  if (watchMode) {
    // Phase 1 needs its own watcher: client-viz.ts is not in the CLI bundle's
    // module graph (only the generated string is), so the Phase 2 watcher
    // alone would keep serving a stale viz bundle. Rebuilding Phase 1 writes
    // the generated module, which then triggers Phase 2.
    const vizCtx = await context({
      ...vizBuildOptions,
      plugins: [
        {
          name: 'write-generated-viz',
          setup(b) {
            b.onEnd(async (result) => {
              if (result.errors.length === 0) {
                await writeGeneratedViz(result)
              }
            })
          },
        },
      ],
    })
    await vizCtx.watch()

    console.log('Phase 2: Building CLI (watch mode)...')
    const ctx = await context(cliBuildOptions)
    await ctx.watch()
    console.log('CLI built. Watching for changes (Ctrl+C to stop)')
  } else {
    console.log('Phase 2: Building NeoFermi CLI...')
    try {
      await build(cliBuildOptions)
      console.log('CLI built successfully: bin/neoferminb.cjs')
    } catch (error) {
      console.error('Build failed:', error)
      process.exit(1)
    }
  }
}

buildCli()
